Ros2 new
RoboStack/jupyter-ros pull request #113
Opened 2022-07-29 08:59 UTC by ldania

File restructure:
Contains the Publisher, Subcriber module and an Example Notebook for these modules

Have dificulty installing via development mode. Could you test it on your end?

2022-07-29 09:02 UTC, ldania commented
Turtle_sim and Turtle Notebooks do not to be added, but should be functional.

2022-07-29 10:28 UTC, ihuicatl commented
Thanks @ldania. We can do some testing on our end, no problem. We also just updated the documentation in case it might help you install in development mode https://jupyter-ros.readthedocs.io/en/latest/dev_installation.html

2022-07-29 11:50 UTC, hbcarlos commented
Thank you so much @ldania! I'll look into this as soon as possible!

2022-08-01 13:46 UTC, ihuicatl requested changes
Thank you so much for your PR! I added a few comments for things that need to change in order to get everything working. I'll review again once the changes are made. If you need any more help, please let us know :smiley:

2022-08-01 13:46 UTC, ihuicatl commented on jupyros/ros2/Publisher.py
> +    def __send_msg(self, _) -> None:
Is there a particular reason for having two `send_msg` functions?

2022-08-01 13:46 UTC, ihuicatl commented on jupyros/ros2/Subscription.py
> +class Subscription():
This should be renamed to `Subscriber` to keep it consistent with `Publisher` and also because in `__init__.py` it is mentioned as `Subscriber`.

2022-08-01 13:46 UTC, ihuicatl commented on jupyros/ros2/__init__.py
> +from ..ros2.Subcriber import *
Cannot import because of typo in Sub`s`criber

2022-08-01 13:46 UTC, ihuicatl commented on notebooks/Ros2 Pub_Sub_Communication.ipynb
> +      "The rospy package is not found in your $PYTHONPATH. Subscribe and publish are not going to work.\n",
It is highly recommended to clean all of the cell outputs beforehand.

2022-08-01 13:46 UTC, ihuicatl commented on notebooks/Ros2 Pub_Sub_Communication.ipynb
> +    "sys.path.append(\"./../../\")\n",
Please do not include relative paths. Without any instructions, it is not possible to determine which directory is supposed to be appended.

2022-08-01 13:46 UTC, ihuicatl commented on notebooks/Ros2 Pub_Sub_Communication.ipynb
> +
The publisher and subscriber are not working. It returns a TypeError
```
TypeError: Expected <class 'std_msgs.msg._string.String'>, got <class 'str'>
```

2022-08-01 13:46 UTC, ihuicatl commented on notebooks/ROS2_Turtlesim.ipynb
> +{
Based on the commit messages, it does not seem like this file and `turtle_sim.py` were meant to be included in this PR. Please remove if necessary.

2022-08-09 13:17 UTC, closed without merging